config/routes.rb
Rails.application.routes.draw do
  # get 'subtype/index'
  # get 'subtype/show'
  # get 'operators/index'
  # get 'operators/show'

  resources :subtypes, only: %i[index show]

  resources :operators, only: %i[index show]

  resources :pages, except: [:show]

  get "/pages/:permalink" => "pages#permalink", as: :permalink

  resources :aircrafts, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :origin_countries, only: %i[index show]

  root to: "home#index"
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
  belongs_to :origin_country
  has_many :aircraft_subtypes
  has_many :subtypes, through: :aircraft_subtypes
  has_many :aircraft_operators
  has_many :operators, through: :aircraft_operators

  validates :name, :aircraft_type, presence: true
  validates :service_start, :units_build, numericality: { only_integer: true }
  validates :unit_price, numericality: { greater_than_or_equal_to: 0 }

  def subtype_list
    subtypes.map(&:name).join(", ")
  end

  def operator_list
    operators.map(&:name).join(", ")
  end
end

app/models/aircraft_operator.rb
class AircraftOperator < ApplicationRecord
  belongs_to :aircraft
  belongs_to :operator
end

app/models/aircraft_subtype.rb
class AircraftSubtype < ApplicationRecord
  belongs_to :aircraft
  belongs_to :subtype
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :aircraft_operators
  has_many :aircrafts, through: :aircraft_operators

  validates :name, presence: true, uniqueness: true
end

app/models/origin_country.rb
class OriginCountry < ApplicationRecord
  has_many :aircrafts
  validates :name, presence: true, uniqueness: true

  def self.orderd_by_aircrafts
    self.select("origin_countries.*")
        .select("COUNT(origin_countries.id) as aircraft_count")
        .left_joins(:aircrafts)
        .group("origin_countries.id")
        .order("aircraft_count DESC")
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/subtype.rb
class Subtype < ApplicationRecord
  has_many :aircraft_subtypes
  has_many :aircrafts, through: :aircraft_subtypes

  validates :name, presence: true, uniqueness: true
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  def index
    @aircrafts = Aircraft.includes(:origin_country).order("name").includes(:operators).includes(:subtypes).page(params[:page])
  end

  def show
    @aircraft = Aircraft.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @aircrafts = Aircraft.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages

  def cms_pages
    Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @aircrafts = Aircraft.includes(:origin_country)
                         .order("units_build DESC")
                         .limit(10)

    @origin_countries = OriginCountry.orderd_by_aircrafts
                                     . limit(10)
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def index
    @operators = Operator.all
  end

  def show
    @operator = Operator.find(params[:id])
  end
end

app/controllers/origin_countries_controller.rb
class OriginCountriesController < ApplicationController
  def index
    @origin_countries = OriginCountry.orderd_by_aircrafts
  end

  def show
    @origin_country = OriginCountry.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "12345", except: [:show]
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/subtypes_controller.rb
class SubtypesController < ApplicationController
  def index
    @subtypes = Subtype.all
  end

  def show
    @subtype = Subtype.find(params[:id])
  end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/origin_countries_helper.rb
module OriginCountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subtypes_helper.rb
module SubtypesHelper
end

app/views/aircrafts/_aircraft.html.erb
<h2 class="title is-2">
  <% if show_link %>
    <%= link_to aircraft.name, aircraft %>
  <% else %>
    <%= aircraft.name  %>
  <% end %>
</h2>

<p>
  <strong>Type:</strong>
  <%= aircraft.aircraft_type %>
</p>

<p>
  <strong>Sub-types:</strong>
  <% countSubtypes = aircraft.subtypes.count %>
  <% aircraft.subtypes.each do |s| %>
    <% if countSubtypes > 1 %>
    <%= link_to s.name, subtype_path(s)%>,
    <% else %>
    <%= link_to s.name, subtype_path(s)%>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Started service at:</strong>
  <%= aircraft.service_start %>
</p>

<p>
  <strong>Units build:</strong>
  <%= aircraft.units_build %>
</p>

<p>
  <strong>Unit Cost:</strong>
  <%= number_to_currency aircraft.unit_price %>
</p>

<p>
  <strong>country of origin:</strong>
  <%= link_to aircraft.origin_country.name, aircraft.origin_country %>
</p>

<p>
  <strong>Operators:</strong>
  <% countOperators = aircraft.operators.count %>
  <% aircraft.operators.each do |o| %>
    <% if countOperators > 1 %>
    <%= link_to o.name, operator_path(o)%>,
    <% else %>
    <%= link_to o.name, operator_path(o)%>
    <% end %>
  <% end %>
</p>

<hr>

app/views/aircrafts/index.html.erb
<h2 class="title is-2">World War II Aircrafts</h2>

<%= paginate @aircrafts%>
<%= render partial: 'aircraft', collection: @aircrafts, locals: {show_link: true} %>
<%= paginate @aircrafts%>

app/views/aircrafts/search.html.erb
<p class="mb-5">Found <%= pluralize(@aircrafts.count, 'Aircraft') %> when searching for: <%= params[:keywords]%></p>

<ul>
  <% @aircrafts.each do |aircraft| %>
    <li><%= link_to aircraft.name, aircraft %></li>
    <% end %>
</ul>

app/views/aircrafts/show.html.erb
<% content_for(:html_title) { @aircraft.name} %>

<%= render partial: 'aircraft', object: @aircraft, locals: {show_link: false}%>

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Most Produced Aircrafts</h2>
      <ol class="ml-5">
        <%  @aircrafts.each do |aircraft| %>
          <li>
            <%= link_to aircraft.name, aircraft %>
            <em>(<%= aircraft.origin_country.name %>)</em>
          </li>
        <% end %>
      </ol>
      <p class="mt-5">
        <strong><%= link_to 'List of all aircrafts', aircrafts_path %></strong></p>
  </div>

  <div class="column">
    <h2 class="title is-2">Countires with most aircraft types</h2>
      <ol class="ml-5">
        <%= render @origin_countries %>
      </ol>
      <p class="mt-5"><strong><%= link_to 'List of all Countries', origin_countries_path %></strong></p>
  </div>
</div>

app/views/operators/index.html.erb
<h2 class="title is-2">Operators</h2>

<ul class="ml-5">
<% @operators.each do |operator| %>
    <li>
      <%= link_to operator.name, operator %>
    </li>
  <% end %>
</ul>

app/views/operators/show.html.erb
<% content_for(:html_title) { @operator.name} %>
<h2 class="title is-2"><%= @operator.name %> operated <%= @operator.aircrafts.count %> aircrafts types.</h2>


<div class="content">
  <ul>
    <% @operator.aircrafts.each do |aircraft| %>
      <li>
      <%= link_to aircraft.name, aircraft %>
      <em>(<%= aircraft.origin_country.name %>)</em>
      </li>
    <% end %>
  </ul>
</div>

app/views/origin_countries/_origin_country.html.erb
<li><%= link_to origin_country.name, origin_country %>
      <em>(<%= pluralize origin_country.aircraft_count, "aircraft type" %>)</em>
  </li>

app/views/origin_countries/index.html.erb
<h2 class="title is-2">Countries</h2>

<ol class="ml-5">
  <%= render @origin_countries  %>

</ol>

app/views/origin_countries/show.html.erb
<% content_for(:html_title) { @origin_country.name} %>
<h2 class="title is-2"><%= @origin_country.name %> made <%= @origin_country.aircrafts.count %> aircrafts.</h2>


<div class="content">
  <ul>
    <% @origin_country.aircrafts.each do |aircraft| %>
      <li><%= link_to aircraft.name, aircraft %></li>
    <% end %>
  </ul>
</div>

app/views/subtypes/index.html.erb
<h2 class="title is-2">Subtypes</h2>

<ul class="ml-5">
<% @subtypes.each do |subtype| %>
    <li>
      <%= link_to subtype.name, subtype %>
    </li>
  <% end %>
</ul>

app/views/subtypes/show.html.erb
<% content_for(:html_title) { @subtype.name} %>
<h2 class="title is-2">Subtype of <%= @subtype.name %> include <%= @subtype.aircrafts.count %> aircrafts types.</h2>


<div class="content">
  <ul>
    <% @subtype.aircrafts.each do |subtype| %>
      <li>
      <%= link_to subtype.name, subtype %>

      </li>
    <% end %>
  </ul>
</div>