config/routes.rb
Rails.application.routes.draw do
  # get 'subtype/index'
  # get 'subtype/show'
  # get 'operators/index'
  # get 'operators/show'

  resources :subtypes, only: %i[index show]

  resources :operators, only: %i[index show]

  resources :pages, except: [:show]

  get "/pages/:permalink" => "pages#permalink", as: :permalink

  resources :aircrafts, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :origin_countries, only: %i[index show]

  root to: "home#index"
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
  belongs_to :origin_country
  has_many :aircraft_subtypes
  has_many :subtypes, through: :aircraft_subtypes
  has_many :aircraft_operators
  has_many :operators, through: :aircraft_operators

  validates :name, :aircraft_type, presence: true
  validates :service_start, :units_build, numericality: { only_integer: true }
  validates :unit_price, numericality: { greater_than_or_equal_to: 0 }

  def subtype_list
    subtypes.map(&:name).join(", ")
  end

  def operator_list
    operators.map(&:name).join(", ")
  end
end

app/models/aircraft_operator.rb
class AircraftOperator < ApplicationRecord
  belongs_to :aircraft
  belongs_to :operator
end

app/models/aircraft_subtype.rb
class AircraftSubtype < ApplicationRecord
  belongs_to :aircraft
  belongs_to :subtype
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :aircraft_operators
  has_many :aircrafts, through: :aircraft_operators

  validates :name, presence: true, uniqueness: true
end

app/models/origin_country.rb
class OriginCountry < ApplicationRecord
  has_many :aircrafts
  validates :name, presence: true, uniqueness: true

  def self.orderd_by_aircrafts
    self.select("origin_countries.*")
        .select("COUNT(origin_countries.id) as aircraft_count")
        .left_joins(:aircrafts)
        .group("origin_countries.id")
        .order("aircraft_count DESC")
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/subtype.rb
class Subtype < ApplicationRecord
  has_many :aircraft_subtypes
  has_many :aircrafts, through: :aircraft_subtypes

  validates :name, presence: true, uniqueness: true
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  def index
    @aircrafts = Aircraft.includes(:origin_country).order("name").includes(:operators).includes(:subtypes).page(params[:page])
  end

  def show
    @aircraft = Aircraft.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @aircrafts = Aircraft.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @aircrafts = Aircraft.includes(:origin_country)
                         .order("units_build DESC")
                         .limit(10)

    @origin_countries = OriginCountry.orderd_by_aircrafts
                                     . limit(10)
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def index
    @operators = Operator.all
  end

  def show
    @operator = Operator.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "12345", except: [:show]
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/subtypes_controller.rb
class SubtypesController < ApplicationController
  def index
    @subtypes = Subtype.all
  end

  def show
    @subtype = Subtype.find(params[:id])
  end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/origin_countries_helper.rb
module OriginCountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subtypes_helper.rb
module SubtypesHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p>
    <em>all rights reserved</em>
  </p>
  <ul class="mt-5">
    <li><%= link_to 'home', root_path %></li>
    <li><%= link_to 'List of all aircrafts', aircrafts_path %></li>
    <li><%= link_to 'List of all origin countries', origin_countries_path %></li>
    <li><%= link_to 'List of all operators', operators_path %></li>
    <li><%= link_to 'List of all Subtypes', subtypes_path %></li>
    <% cms_pages.each do |page| %>
      <li><%= link_to page.title, permalink_path(page.permalink) %></li>
    <% end %>
  </ul>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar is-transparent">
  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="<%= root_path %>">
        Home
      </a>
      <a class="navbar-item" href="<%= aircrafts_path %>">
        Aircrafts
      </a>
      <a class="navbar-item" href="<%= subtypes_path %>">
        Subtypes
      </a>
      <a class="navbar-item" href="<%= origin_countries_path %>">
        Countries
      </a>
      <a class="navbar-item" href="<%= operators_path %>">
        Operators
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Docs
        </a>
        <div class="navbar-dropdown is-boxed">
          <a class="navbar-item" href="<%= permalink_path('about_the_data') %>">
            About
          </a>
          <a class="navbar-item" href="<%= permalink_path('contact_us') %>">
            Contact
          </a>
          <a class="navbar-item">
            Form
          </a>
           <hr class="navbar-divider">
          <a class="navbar-item is-active" href="<%= pages_path %>">
            Admin
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %> WWII Aircrafts </title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <section class="section">
      <div class="container">
        <h1 class="title is-1"><%= link_to 'World War II Aircrafts', root_path %></h1>

        <%= render partial: 'common/navbar' %>

        <%= form_with(url: search_aircrafts_path, method: :get, local: true) do %>
        <div class="field is-grouped mb-5">
          <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Aircrafts') %>
          </div>

          <div>
            <%= submit_tag("Search", class: "button is-primary") %>
          </div>
        </div>
          <% end %>

        <%= yield %>

        <%= render partial: 'common/footer' %>
      </div>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "label"  %>
    <%= form.text_area :content, class: "textarea" %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: "label" %>
    <%= form.text_field :permalink, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2 class="title is-4">Editing Page</h2>

<%= render 'form', page: @page %>

<p class="mt-5">
  <%= link_to 'Back', pages_path, class: "button is-primary" %>
</p>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4"> CMS Pages</h2>
<%= link_to 'New Page', new_page_path, class: "button is-primary" %>

<hr>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>

    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-warning' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/new.html.erb
<h2 class="title is-4">New Page</h2>

<%= render 'form', page: @page %>
<p class="mt-5">
  <%= link_to 'Back', pages_path, class: "button is-primary"  %>
</p>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4"><%= @page.title %></h2>

<p class="mt-5"><%= @page.content %></p>